[package]
name = "autumn-homepage"
version = "0.1.0"
authors = ["hyziri <hyziri@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "migration", "entity"]

[dependencies]
# === Default ===
dioxus = { version = "0.6.3", features = ["fullstack", "router"] }
dioxus-logger = "0.6.2"
dioxus-document = { version = "0.6.3" }
dioxus-free-icons = { version = "0.9.0", features = [
    "font-awesome-brands",
    "font-awesome-solid",
] }

# 3rd Party crates
serde = { version = "1.0.225", features = ["derive"] }
chrono = { version = "0.4.42", features = ["serde"] }

# === Server ===
dioxus-cli-config = { version = "0.6.3", optional = true }

## Workspace
migration = { path = "migration", optional = true }
entity = { path = "entity", optional = true }

## Autumn Crates
eve_esi = { version = "0.4.2", optional = true }

## 3rd Party Crates
dotenvy = { version = "0.15.7", optional = true }
tokio = { version = "1.47.1", features = ["macros"], optional = true }
reqwest = { version = "0.12.23", features = ["json"], optional = true }
serde_json = { version = "1.0.145", optional = true }
thiserror = { version = "2.0.16", optional = true }
mockito = { version = "1.7.0", optional = true }
log = { version = "0.4.28", optional = true }
sea-orm = { version = "1.1.16", optional = true }
job_scheduler = { version = "1.2.1", optional = true }
tokio-cron-scheduler = { version = "0.14.0", optional = true }
axum = { version = "0.7.9", optional = true }
dioxus-charts = "0.3.1"

[features]
default = []
server = [
    "dioxus/server",
    "migration",
    "entity",
    "eve_esi",
    "dotenvy",
    "tokio",
    "reqwest",
    "serde_json",
    "thiserror",
    "mockito",
    "log",
    "sea-orm",
    "job_scheduler",
    "tokio-cron-scheduler",
    "axum",
    "dioxus-cli-config",
]
web = ["dioxus/web"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
