# Development version of docker-compose.yml
#
# Starts the containers but on ports directly rather than with traefik labels
# - Homepage is on port 8080
# - API is on port 8000

services:
  autumn-homepage:
    build: ./web
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f -H 'Accept: text/html' http://localhost:8080 || exit 1",
        ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - autumn-homepage-api
    networks:
      - autumn_homepage
    ports:
      - 8080:8080

  autumn-homepage-api:
    build: ./api
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f -H 'Accept: text/html' http://localhost:8000 || exit 1",
        ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - postgres
    networks:
      - autumn_homepage
    ports:
      - 8000:8000

  postgres:
    image: postgres:latest
    env_file: .env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - autumn_homepage

volumes:
  postgres_data_dev:

networks:
  autumn_homepage:
