services:
  autumn-homepage:
    build: .
    restart: unless-stopped
    environment:
      - CONTACT_EMAIL=${CONTACT_EMAIL}
    volumes:
      - autumn-homepage:/app/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f -H 'Accept: text/html' http://localhost:8080 || exit 1",
        ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=Host(`${DOMAIN}`) && !PathPrefix(`/api`)
      - traefik.http.routers.web.entrypoints=websecure
      - traefik.http.routers.web.tls.certresolver=primary
      - traefik.http.services.web.loadbalancer.server.port=8080

volumes:
  autumn-homepage:

networks:
  traefik:
    external: true
