[package]
name = "autumn-homepage"
version = "0.1.0"
authors = ["hyziri <hyziri@protonmail.com>"]
edition = "2021"

[dependencies]
dioxus = { version = "0.6.3", features = ["fullstack", "router"] }
dioxus-document = { version = "0.6.3" }
dioxus-free-icons = { version = "0.9.0", features = [
    "font-awesome-brands",
    "font-awesome-solid",
] }
dioxus-charts = "0.3.1"

serde = { version = "1.0.225", features = ["derive"] }
chrono = { version = "0.4.42", features = ["serde"] }
reqwest = { version = "0.12.22", features = ["json"] }
tracing = "0.1.41"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
